version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456789Vl@
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456789Vl@
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
